### ISSUE TITLE
nejhorsy dev

### ISSUE THREAD

**Issue by Crystallek** [takoda121/rooinj#1]
nefunguje mi toto repo plz help

**Comment by Crystallek** [comment]
fuj toto je fakt odpadni dev ani mi nepomuze :sob: .

**Comment by takoda121** [comment]
> fuj toto je fakt odpadni dev ani mi nepomuze 😭 .

PANE TOTO JE NEJDULEZITEJSI REPO NA SVJETE!

**Comment by Crystallek** [comment]
OMG AHA SORRY
